// Central data store — admin edits persist to localStorage on client
// On first load, seeded from SEED_PACKAGES

export const SEED_PACKAGES = [
  {
    id: 'goa-beach-bliss',
    destination: 'Goa',
    badge: 'Beach Getaway',
    badgeColor: '#2e9e7a',
    duration: '4 Days & 3 Nights',
    title: 'Goa Beach Bliss',
    subtitle: 'Sun, Sand & Spice',
    hotels: '2N North Goa · 1N South Goa',
    originalPrice: 18000,
    salePrice: 12500,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1400&q=85',
    overview: 'Lose yourself in the golden beaches, Portuguese architecture, and legendary nightlife of Goa. From the vibrant shacks of North Goa to the serene stretches of the South, this package covers the best of India\'s party capital.',
    highlights: ['Baga & Anjuna Beach visits', 'Old Goa churches heritage walk', 'Dudhsagar Waterfalls day trip', 'Sunset cruise on Mandovi River', 'South Goa — Palolem & Colva'],
    inclusions: ['3 nights accommodation', 'Daily breakfast', 'Airport / station transfers', 'Sightseeing as per itinerary', 'Local transport'],
    exclusions: ['Flights / trains', 'Meals not mentioned', 'Personal expenses', 'Adventure activities'],
    itinerary: [
      { day: 1, title: 'Arrival in Goa — North Goa Beaches', description: 'Arrive at Goa Airport / Madgaon Station. Check into your North Goa resort. Head to Baga Beach for your first Goa sunset. Evening at leisure — explore the famous shacks and beach bars.', activities: ['Airport pickup', 'Hotel check-in', 'Baga Beach sunset', 'Dinner at beach shack'] },
      { day: 2, title: 'North Goa Exploration', description: 'Full day exploring North Goa\'s iconic spots. Morning visit to Anjuna Flea Market (Wed/Sat) or Calangute. Afternoon heritage walk through Old Goa — Basilica of Bom Jesus & Se Cathedral.', activities: ['Anjuna / Calangute Beach', 'Old Goa churches', 'Fort Aguada', 'Sunset cruise on Mandovi River'] },
      { day: 3, title: 'Dudhsagar Day Trip → South Goa', description: 'Early morning excursion to the spectacular Dudhsagar Waterfalls. Return and check out, drive to peaceful South Goa. Afternoon at Palolem Beach — the most picturesque crescent in Goa.', activities: ['Dudhsagar Waterfalls jeep ride', 'Spice plantation visit', 'Palolem Beach arrival', 'Evening at leisure'] },
      { day: 4, title: 'South Goa & Departure', description: 'Leisurely morning at Colva or Benaulim Beach. After checkout, explore the local market. Transfer to airport/station for onward journey.', activities: ['Colva / Benaulim Beach', 'Local market browsing', 'Checkout & transfer'] },
    ],
  },
  {
    id: 'goa-party-escape',
    destination: 'Goa',
    badge: 'Weekend Special',
    badgeColor: '#2e9e7a',
    duration: '3 Days & 2 Nights',
    title: 'Goa Party Escape',
    subtitle: 'Quick North Goa Getaway',
    hotels: '2N North Goa',
    originalPrice: 12000,
    salePrice: 8500,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=1400&q=85',
    overview: 'The perfect weekend escape to North Goa. Pack in beaches, heritage, boat rides and nightlife into an action-packed 3-day itinerary.',
    highlights: ['Baga, Calangute & Anjuna Beaches', 'Nightlife at Tito\'s Lane', 'Fort Aguada sunset', 'Mandovi River cruise', 'Seafood feast'],
    inclusions: ['2 nights accommodation', 'Daily breakfast', 'Airport transfers', 'Sightseeing'],
    exclusions: ['Flights / trains', 'Meals not mentioned', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival & Beach Time', description: 'Land in Goa, check in, and hit the beaches immediately. Evening Tito\'s Lane or Baga nightlife.', activities: ['Hotel check-in', 'Calangute Beach', 'Sunset at Baga', 'Tito\'s nightlife'] },
      { day: 2, title: 'Heritage & Beaches', description: 'Morning Old Goa, afternoon Anjuna, evening Mandovi River cruise.', activities: ['Basilica of Bom Jesus', 'Fort Aguada', 'Anjuna Beach', 'Sunset cruise'] },
      { day: 3, title: 'Last Morning & Departure', description: 'Leisurely beach morning and departure by afternoon.', activities: ['Morning beach walk', 'Breakfast', 'Checkout & transfer'] },
    ],
  },
  {
    id: 'gokarna-coastal-retreat',
    destination: 'Gokarna',
    badge: 'Beach + Temple',
    badgeColor: '#e8520a',
    duration: '3 Days & 2 Nights',
    title: 'Gokarna Coastal Retreat',
    subtitle: 'The Offbeat Spiritual Coast',
    hotels: '2N Gokarna Beach',
    originalPrice: 10000,
    salePrice: 7200,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?w=1400&q=85',
    overview: 'Gokarna is Goa\'s quieter, spiritual cousin. Home to Om Beach, Kudle Beach, and the ancient Mahabaleshwar temple — it\'s the perfect blend of beach vibes and sacred energy.',
    highlights: ['Om Beach sunrise yoga', 'Trek to Half Moon & Paradise Beach', 'Mahabaleshwar Temple visit', 'Kudle Beach sunset', 'Kayaking & water sports'],
    inclusions: ['2 nights beach resort', 'Daily breakfast', 'Station pickup/drop', 'Beach trek guide'],
    exclusions: ['Trains / buses', 'Meals not mentioned', 'Water sports costs'],
    itinerary: [
      { day: 1, title: 'Arrival at Gokarna', description: 'Arrive at Gokarna Station. Check into beach resort near Om Beach. Evening visit to Mahabaleshwar Temple, then stroll along the main beach.', activities: ['Station pickup', 'Hotel check-in', 'Mahabaleshwar Temple', 'Om Beach evening'] },
      { day: 2, title: 'Beach Trek Day', description: 'Early morning sunrise yoga on Om Beach. Trek along the cliffside trail to Half Moon Beach and Paradise Beach. Afternoon return via boat or trail.', activities: ['Sunrise yoga on Om Beach', 'Cliff trek to Half Moon Beach', 'Paradise Beach stop', 'Kayaking & swimming', 'Sunset at Kudle Beach'] },
      { day: 3, title: 'Peaceful Morning & Departure', description: 'Final morning at leisure — swim or meditate. Checkout and transfer to Gokarna Road station.', activities: ['Morning beach walk', 'Local market', 'Checkout', 'Station drop'] },
    ],
  },
  {
    id: 'gokarna-yoga-wellness',
    destination: 'Gokarna',
    badge: 'Wellness',
    badgeColor: '#e8520a',
    duration: '4 Days & 3 Nights',
    title: 'Gokarna Yoga & Wellness',
    subtitle: 'Detox, Breathe & Reconnect',
    hotels: '3N Gokarna Eco Resort',
    originalPrice: 15000,
    salePrice: 11000,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=85',
    overview: 'A deeply restorative escape combining yoga, beach treks, temple visits, and clean organic eating. Gokarna\'s untouched coastline is the perfect backdrop for this wellness retreat.',
    highlights: ['Daily morning yoga sessions', 'Om, Kudle & Half Moon Beach', 'Temple walks & meditation', 'Organic meals', 'Bonfire on the beach'],
    inclusions: ['3 nights eco resort', 'All meals', 'Yoga sessions', 'Beach treks', 'Transfers'],
    exclusions: ['Trains / buses', 'Personal expenses', 'Spa treatments'],
    itinerary: [
      { day: 1, title: 'Arrival & Orientation', description: 'Settle into the eco resort, welcome yoga session at sunset.', activities: ['Pickup', 'Check-in', 'Orientation walk', 'Sunset yoga', 'Organic dinner'] },
      { day: 2, title: 'Yoga & Temple', description: 'Morning yoga, afternoon temple visit, evening Kudle Beach.', activities: ['Morning yoga', 'Mahabaleshwar Temple', 'Kudle Beach', 'Meditation session'] },
      { day: 3, title: 'Beach Trek', description: 'Trek to Half Moon and Paradise Beaches, beach bonfire evening.', activities: ['Cliff trek', 'Half Moon Beach', 'Paradise Beach', 'Beach bonfire'] },
      { day: 4, title: 'Departure', description: 'Final yoga session, healthy breakfast, and departure.', activities: ['Farewell yoga', 'Breakfast', 'Checkout', 'Transfer'] },
    ],
  },
  {
    id: 'chikmagalur-coffee-trail',
    destination: 'Chikmagalur',
    badge: 'Hill Station',
    badgeColor: '#2e3da8',
    duration: '3 Days & 2 Nights',
    title: 'Chikmagalur Coffee Trail',
    subtitle: 'Misty Hills & Aromatic Estates',
    hotels: '2N Chikmagalur Estate Stay',
    originalPrice: 11000,
    salePrice: 8000,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1598894168197-84da3a01e3bb?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1598894168197-84da3a01e3bb?w=1400&q=85',
    overview: 'The birthplace of Indian coffee — Chikmagalur is a misty hill paradise draped in coffee and spice estates. Trek through shola forests, visit historic temples, and wake up to the aroma of fresh coffee.',
    highlights: ['Coffee estate tour & tasting', 'Mullayanagiri peak trek', 'Baba Budangiri caves visit', 'Hebbe Falls day trip', 'Sunset at Kemmangundi'],
    inclusions: ['2 nights estate homestay', 'Daily breakfast & dinner', 'Coffee estate tour', 'Local sightseeing', 'Transfers'],
    exclusions: ['Travel to Chikmagalur', 'Lunch', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival & Coffee Estate Tour', description: 'Arrive at Chikmagalur. Check into the coffee estate homestay. Afternoon guided coffee estate tour — learn the process from cherry to cup. Evening campfire with fresh filter coffee.', activities: ['Pickup from Chikmagalur town', 'Estate homestay check-in', 'Coffee estate guided tour', 'Coffee tasting session', 'Campfire evening'] },
      { day: 2, title: 'Mullayanagiri Trek & Hebbe Falls', description: 'Early morning drive to Mullayanagiri — the highest peak in Karnataka. Trek to the summit for panoramic views. Afternoon drive to the magical Hebbe Falls inside a private coffee estate.', activities: ['Mullayanagiri sunrise trek (1900m)', 'Summit views & photography', 'Hebbe Falls (Dodda Hebbe & Chikka Hebbe)', 'Estate lunch', 'Return to homestay'] },
      { day: 3, title: 'Baba Budangiri & Departure', description: 'Morning visit to the sacred Baba Budangiri caves — where coffee was first brought to India. Explore Kemmangundi on the way. Post-lunch departure.', activities: ['Baba Budangiri Dargah & caves', 'Kemmangundi viewpoint', 'Local spice market', 'Checkout & departure'] },
    ],
  },
  {
    id: 'chikmagalur-weekend',
    destination: 'Chikmagalur',
    badge: 'Weekend Trek',
    badgeColor: '#2e3da8',
    duration: '2 Days & 1 Night',
    title: 'Chikmagalur Weekend Escape',
    subtitle: 'Quick Green Hills Getaway',
    hotels: '1N Chikmagalur Homestay',
    originalPrice: 7500,
    salePrice: 5500,
    priceNote: 'Per Person',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=700&q=80',
    heroImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1400&q=85',
    overview: 'The perfect quick escape into the misty hills of Chikmagalur. Pack in a coffee estate, a waterfall, and a peak trek in just two days.',
    highlights: ['Coffee estate experience', 'Hebbe Falls trek', 'Mullayanagiri viewpoint', 'Sunset views', 'Cozy homestay'],
    inclusions: ['1 night homestay', 'Breakfast & dinner', 'Coffee tour', 'Local guide'],
    exclusions: ['Travel', 'Lunch', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival, Coffee & Falls', description: 'Arrive, check in, coffee estate tour, Hebbe Falls, campfire.', activities: ['Check-in', 'Coffee tour', 'Hebbe Falls', 'Campfire dinner'] },
      { day: 2, title: 'Mullayanagiri & Departure', description: 'Morning Mullayanagiri viewpoint, breakfast, and departure.', activities: ['Mullayanagiri viewpoint', 'Breakfast', 'Checkout', 'Departure'] },
    ],
  },
]
